version: '3.8'

services:
  database:
    image: "postgres"
    ports:
      - 5400:5432
    environment: 
      POSTGRES_USER: score
      POSTGRES_PASSWORD: score123
      POSTGRES_DB: thescore

  score_server:
    container_name: score_server
    depends_on: 
      - database
    links:
      - database
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        TYPEORM_HOST: database
        TYPEORM_USERNAME: score
        TYPEORM_PASSWORD: score123
        TYPEORM_DATABASE: thescore
        TYPEORM_PORT: 5432
    ports:
      - 4001:4000

  score_client:
    container_name: score_client
    depends_on: 
        - score_server
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_ENDPOINT: http://localhost:4001
    ports:
      - 1300:80
    